### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *torch.from_array() / tensor.numpy()*

In [9]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
arr = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(arr)

print("numpy array: ", arr)
print("tensor : ", tensor)
print(tensor.numpy())

numpy array:  [[1 2 3]
 [4 5 6]]
tensor :  tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [10]:
# Example 1 - 將Tensor改變形狀
a = torch.Tensor([1, 2, 3, 4])
print(a)
# tensor([1., 2., 3., 4.])

b = torch.unsqueeze(a, 1)
print(b)

tensor([1., 2., 3., 4.])
tensor([[1.],
        [2.],
        [3.],
        [4.]])


In [11]:
# Example 2 - 去除維度為1的向量
m = torch.zeros(2, 1, 2, 1, 2)
print(m.size())  # torch.Size([2, 1, 2, 1, 2])

n = torch.squeeze(m)
print(n.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])


### Function 3 - tensor.transpose() / tensor.permute()

In [12]:
# Example 1 - 將矩陣內部元素調換位置
torch.randn(2,3,4,5).permute(3,2,0,1).shape

torch.Size([5, 4, 2, 3])

In [15]:
# Example 2 - 用transpose()實現permute()效果, 只是transpose()只能兩兩對換
torch.randn(2,3,4,5).transpose(3,0).transpose(2,1).transpose(3,2).shape

torch.Size([5, 4, 2, 3])

### Function 4 - torch.reshape() / tensor.view()

In [14]:
# Example 1 - 改變Tensor的形狀
print(torch.arange(10).reshape((2,5)))
print(torch.arange(10).reshape(5, -1))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [16]:
# Example 2 - 相當於numpy中resize()的功能
a=torch.Tensor([[[1,2,3],[4,5,6]]])
b=torch.Tensor([1,2,3,4,5,6])

print(a.view(1,6))
print(b.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])
